### ISSUE TITLE
UI example mouse clicks won't work when isometric_rpg example playerEntity is enabled

### ISSUE THREAD

**Issue by jkalkhof** [melonjs/melonJS#952] opened 2018-10-01 23:12 UTC
#### OS platform / Browser  
Windows 10/Chrome Version 69.0.3497.100 (Official Build) (64-bit)

#### melonJS version 
master branch - 10/1/2018 -  melonjs 6.2.0

#### Bug description  
UI example mouse clicks won't work with simulation_rpg example

#### Steps to reproduce the bug
I have put in a pull request 951 - code which reproduces the problem.
(see examples/isometric_rpg_ui)
https://github.com/melonjs/melonJS/pull/951

change to line 43 of game.js:
me.pool.register("mainPlayer", game.PlayerEntity);
to
me.pool.register("mainPlayer", me.Entity);
will prevent the conflict of playerEntity affecting the UI mouse clicks.

#### Console log Extract 
-no errors in log

**Comment by obiot** [comment] 2018-10-03 05:49
oh... weird & interesting ! thanks for the report I will have a look at it.

**Comment by obiot** [comment] 2018-10-03 05:50
weird because there are at least a couple of isometric project going on those days, and none of the developers reported any issue, so maybe it's just a bug in the isometric example, let's hope for it :)

**Comment by jkalkhof** [comment] 2018-10-04 00:30
Looks like I found a clue:
if I disable line 25 of UIContainer.js the mouse clicks work:
```
        // causes conflict with game.PlayerEntity
        // this.floating = true;
```
I'm not sure why floating feature of me.Container (me.Renderable) would cause a problem.

**Comment by obiot** [comment] 2018-10-27 01:13
@jkalkhof apologies as I did not have the time yet to go through this one, however I just pushed a few commits with some regression following the viewport change on the master branch. 

it would really be great if you could update your current branch and see if the problem is still there :)

thank you !

**Comment by obiot** [comment] 2022-04-30 00:54
closing this one, which I believe was fixed (can't reproduce the issue on my side)

**Closed by obiot** 2022-04-30 00:54 UTC
Labels: Bug
