### ISSUE TITLE
Cannot hide or interact with debugPanel

### ISSUE THREAD

**Issue by cdwuestner** [melonjs/melonJS#888] opened 2017-05-22 00:07 UTC
Hi, I have a game with a title screen and a play screen. The debugPanel works as expected on the title screen, but if I go to the play screen and open the debugPanel (with the 's' key), it is not possible to hide the debugPanel again. If I press the 'h' key, the 'update' and 'draw' fields stop updating but the debugPanel does not disappear. If I press 's' again, the debugPanel fields begin updating again. Additionally, I can never select the "hitbox" or "velocity" fields once I advance to the play screen.

I am currently using the version of melonJS available in the boilerplate, and am experiencing these issues on both Chrome and Firefox. Thank you for your time and consideration.

**Comment by parasyte** [comment] 2017-05-22 01:09
Sounds like you're probably not clearing the screen correctly. You need a background image on your map, or add a me.ColorLayer to the scene. The problem with checkboxes might be related to the other pointer event issues. (Just a guess.)

**Comment by obiot** [comment] 2017-06-16 02:43
the showing/hiding point were addressed through ticket #883. As for the refresh issue, i concur with @parasyte 's feedback. Just tried both Chrome and Firefox, on both Windows 7/10 and OSX 10.x, and could not reproduce any issue, so closing this ticket.

**Closed by obiot** 2017-06-16 02:43 UTC
