### ISSUE TITLE
weird bug in the platformer

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#654] opened 2015-02-17 03:55 UTC
Just noticed a weird bug in the platformer, go to second level, on top of the "brick pyramid", when jumping outside of the screen (on top) some items are disappearing ... I though it was related to the 'alwaysUpdate" flag (which is actually set for the main player), but it seems to be more like only the objects in the same quad are disappearing when the main player is off screen.

**Comment by obiot** [comment] 2015-02-17 04:30
https://github.com/melonjs/melonJS/commit/fa4c9344dd3074976db8a152c3964822d0e2df70#commitcomment-9633172

**Comment by parasyte** [comment] 2015-02-17 05:43
@obiot This seems fixed with the simple patch. I don't think it can cause regressions; resizing the root container is bug.

**Comment by obiot** [comment] 2015-02-17 06:13
indeed, i was just reading the discussion on the chat, and was wondering why the root container needed to be resized, thanks Jason !

**Comment by parasyte** [comment] 2015-02-17 19:53
Reopening this ticket after @agmcleod brought up that it's an insufficient fix for nested containers. The issue is likely related to how containers adjust their bounds to the minimum containing boundary of their children. I don't even know if this behavior is necessary? I seem to remember is was used for `inViewport` testing prior to the introduction of `_absoluteBounds`. Since the latter replaced the former, I suppose we should remove this: https://github.com/melonjs/melonJS/blob/4f115420b3e6dcbfde70b6f4069d74fc23127b91/src/renderable/container.js#L342-L370 (Or rename it)

**Comment by agmcleod** [comment] 2015-02-19 01:16
After my change here, do you think we're good? https://github.com/melonjs/melonJS/commit/34594c60c1b6288d57db81f78b88b27c768c154a

**Comment by parasyte** [comment] 2015-02-19 01:29
@agmcleod On first sight, it seems reasonable to me. I haven't thought through all potential pitfalls, of course. I like it!

**Comment by agmcleod** [comment] 2015-02-19 01:52
Haha yeah, here's hoping :)

**Closed** 2015-02-19 02:12 UTC
