### ISSUE TITLE
Sprite framewidth/frameheight ignored after first use of image

### ISSUE THREAD

**Issue by dynamo-foundation** [melonjs/melonJS#1087] opened 2022-03-07 06:39 UTC
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Any
 
#### melonJS version 
10

#### Bug description  
See attached screencaps.  If a sprite is created using an image and then a second sprite is created using the same image, the framewidth and frameheight settings are ignored on the second sprite.  In the attached example, if I use "ui64" as the image source for the second sprite, the framewidth and frameheight are forced to 64 (the settings from the first sprite).  This forces me to use a differently named copy of the sprite in order to get different framewidths/frameheights.

#### Steps to reproduce the bug
create a sprite with an image and specify a framewidth and frameheight
create a second sprite with the same image and specify a different framewidth and frameheight
dump the points array to the console for the second sprite - you will see the dimensions of the first sprite

#### Console log Extract 
to show possible exception/errors raised by the engine or the browser

##### How to enable/use the console log
* Webkit (Chrome, Safari) : https://developer.chrome.com/devtools
* Opera : http://www.opera.com/dragonfly/documentation/
* FireFox : http://getfirebug.com/enable
* MS (Edge) : https://docs.microsoft.com/en-us/microsoft-edge/f12-devtools-guide/debugger

<img width="722" alt="Capture1" src="https://user-images.githubusercontent.com/81651363/156980802-e414e493-cd0a-4014-9c21-01f0c147ef18.PNG">
<img width="405" alt="Capture2" src="https://user-images.githubusercontent.com/81651363/156980816-b0cd71f3-a5e5-4061-b804-0c0babc48a45.PNG">

**Comment by obiot** [comment] 2022-03-10 01:40
I'm not getting what you do exactly in the code above, but I create to me.Sprite object, using the same image, but specifying different frame width and frame height, I don;'t have any issue on my side...

**Comment by obiot** [comment] 2022-03-10 01:43
oh wait, fuck yes, you are right ! holy cow this is weird 🤦 🥲

**Comment by obiot** [comment] 2022-03-10 02:22
found the issue !

the problem is here:
https://github.com/melonjs/melonJS/blob/master/src/video/texture_cache.js#L51

with the cached texture being retreived only based on the image itself (I mean HTMLImageElement), searching for right texture cached with also width and height should fix it

**Comment by obiot** [comment] 2022-03-10 06:53
and here is a fix for this one (see last commit), not super happy about it though, looks overcomplex (so I'll keep the ticket open for a while), but working for now I guess

**Comment by obiot** [comment] 2022-03-13 07:59
this one done, closing this ticket

**Closed by obiot** 2022-03-13 07:59 UTC
