### ISSUE TITLE
Add support to click events on items in a nested container

### ISSUE THREAD

**Issue by agmcleod** [melonjs/melonJS#611] opened 2014-11-28 23:00 UTC
Maybe #549 will solve this, but kinda needed for menu containers. Might also just be a documentation problem. But if you have an object inside a menu container, and pass `this` to the handler, it tries to use its relative coordinates:

   container.pos = 100,100
   container.childObject.pos = 10, 0

   me.input.registerEventListener("pointer", this, eventHandler);

The this getting passed binds to 10, 0 relative to the canvas, not 110, 100.

**Comment by agmcleod** [comment] 2015-02-11 00:32
Could this now be solved with absolute bounds?

**Comment by obiot** [comment] 2015-12-16 07:15
#118 is done now, but i'm not sure i'm getting how it helps fixing this issue ? (but i'm probably missing something obvious)

**Comment by parasyte** [comment] 2015-12-16 07:59
It made sense from an architectural point of view with #549, and that's what fixed #118.

Anyway, this bug may or may not be easy to fix. As pointed out on the forum, it's caused by relative positioning of children: https://github.com/melonjs/melonJS/blob/2b5277a4c57d08125da9e8d8f83eaea5098c6aa8/src/input/pointer.js#L331 This also causes problems with `floating` children.

**Comment by obiot** [comment] 2016-01-22 08:34
Hi Guys (@parasyte @agmcleod)

here is a fix for it, basically what I did is to add two new properties under the `Event` object that contains the pointer coordinates relatively to the object container. After that a first detection is done using the global (absolute) coordinates on the object bounding box (since it's also in absolute coordinates), and if matching, a second detection is done on the object itself using the relative one
see:https://github.com/melonjs/melonJS/blob/1029594f0f2c50964f4b8bf895860d505ae5b666/src/input/pointer.js#L334-L338

Few questions comments :
- having a function to retrieve the ancestor absolute position is actually quite useful, instead of accessing the private `_absPos` property (any suggestion?)
- i think `gameLocalX/Y` is quite clear in terms of naming, we might as well add a corresponding `getLocalBounds()` ? 

any other code review welcome :)

**Comment by obiot** [comment] 2016-01-22 08:50
we could for example add a `getAncestorBounds()` or (a bit shorter) `getParentBounds()` ?

**Comment by obiot** [comment] 2016-01-22 08:57
I was checking the flash API to get some idea on how to properly define all these things, and noticed that they actually allow to pass an object that than serve as a reference for the given bound coordinates :
http://help.adobe.com/en_US/as2/reference/flashlite/WS5b3ccc516d4fbf351e63e3d118ccf9c47f-7cef.html

which means that mixing their logic and our implementation, we could actually get the object "relative" bound (to the parent container) by using/calling `object.getBounds(object.ancestor)` ?

**Comment by obiot** [comment] 2016-01-22 09:10
or a true/false parameter : 
- `getBounds()` or `getBounds(false)` returns the bounds in absolute coordinates
- `getBounds(true)` returns the bounds in "local" coordinates (relatively to the object parent container)

**Comment by obiot** [comment] 2016-01-26 14:22
unless anyone has any comments, this one is ready to be merged into master

**Comment by obiot** [comment] 2016-01-27 08:30
merged

**Closed by obiot** 2016-01-27 08:30 UTC
