### ISSUE TITLE
Erratic behaviour on Microsoft Edge

### ISSUE THREAD

**Issue by siauderman** [melonjs/melonJS#1003] opened 2020-06-06 09:40 UTC
Sometimes, a completely black screen is displayed; sometimes, there are missing sprites. No errors in console so I couldn't trace what was causing the problems.

I think the problem is Microsoft Edge and not melonjs, but maybe you want to check if you're intending to support Microsoft Edge. If you're not, then never mind.

**Comment by obiot** [comment] 2020-06-06 10:02
Hi, thanks for the report.

Could you copy/paste here the console log information with the melonjs version and the renderer information ?

I was testing edge on windows actually yesterday, using all the current examples, but I did not experienced any issue on my side, it would be great if you could share a minimal version of your game that would allow me to reproduce the issue.

Thanks !

**Comment by obiot** [comment] 2020-06-06 10:05
Just saw this : https://windowsreport.com/microsoft-edge-black-screen/

I wonder if maybe this is the issue as it seems to be driver related

**Comment by siauderman** [comment] 2020-06-08 06:23
vendor.2553edb6.js:7 melonJS v7.1.1 | http://melonjs.org
vendor.2553edb6.js:7 WebGL | Web Audio | pixel ratio 1.25 | desktop | landscape-primary | en-US
vendor.2553edb6.js:7 resolution: requested 1536x754, got 1536x754

There are no errors in console, not sure if it is a bug in Edge or with melonjs.

**Comment by obiot** [comment] 2020-06-10 02:30
this could be a GPU driver related issue, as similar issue have been reported with Edge in the past and one of the fix was to update graphic card drivers.

to valide if this is a browser issue or/and melons specific, did you try any other WebGL based stuff ?  (here is one https://akirodic.com/p/jellyfish/)

Also using the latest 8.0 development version, and after updating your drivers to the latest version, could you try the different renderer (canvas, webgl1 & webgl2) ?
[melonjs8.0-dev.zip](https://github.com/melonjs/melonJS/files/4755836/melonjs8.0-dev.zip)

renderer can be forced using `renderer : me.video.CANVAS` or `renderer : me.video.WEBGL` and for WebGL2 you need to use/add `preferWebGL1 : false`. (with each renderer please also provide the console output)

thanks !

**Comment by obiot** [comment] 2020-07-22 05:34
Hi, so sorry to come back to you so late on this, but I got busy somewhere else and only got back to it a few days ago

Anyway so after a few days trying to find out how to fix either the games or melonJS, the conclusion is that I'm not sure how to do as I'm not even able to find the issue in the first place, the game source code is quite complex, I'm not familiar with quasar, and it's hard to get into it (took me 2 hours to find out where the in-game background was defined), and I did not manage to get the debug plugin to load so that I could see where are the bounding box for all objects (see below on why im mentioning this)

this say, currently my assumption is that object default position is now off following the fix on me.Sprite object on the anchor point (see [here](https://github.com/melonjs/melonJS/commit/72cde7948d5d913ac79f244e86b1eb248e2752e0)) ; we had actually a regression in the 7.x branch where the Anchor Point was off when using directly me.Sprite or be more precise object based on something else than me.Entity (which explains why the tutorial and various example keep working). So behaviour did change, and I think that this might be the issue. Could you have a look at that particular point ? since this is your source code its definitely easier for you to actually change it the proper way (I feel like I'm hacking thing here, and I'm losing tracks of my changes)

Also I did find out that you use `screen` as the div parent for the game canvas (when calling `me.video.init`), where the html "template" uses `q_app` or something, is this not an issue ? what div is melonJS supposed to resides in ?

ps: I added a sprite example now that show proper positioning,  rotation and scaling for sprite using their Anchor Point : https://github.com/melonjs/melonJS/tree/master/examples/sprite

here is also the very latest build (did a few more fixes that don't address this particular point, but still better to have)
[melonjs-8.0-dev.zip](https://github.com/melonjs/melonJS/files/4958018/melonjs-8.0-dev.zip)

**Comment by siauderman** [comment] 2020-07-26 14:07
Dear Olivier,

Thank you very much for your efforts, it is greatly appreciated.

I will try the latest build again.

**Comment by siauderman** [comment] 2020-08-02 09:43
@obiot Still doesn't work, I will try to create a demo in straight JS to demonstrate exactly what is wrong with the scrolling map rendering as well as inability to click anything.

**Comment by obiot** [comment] 2020-08-02 09:45
that would awesome, thank you very much !

**Comment by siauderman** [comment] 2020-08-02 10:32
OK for the scrolling bug I have done a demo.

Canvas shows expected behaviour in this demo.

WebGL both 1 & 2 show incorrect behaviour.

melonJS 8 to be placed in same folder and named melonjs.js.

[index.txt](https://github.com/melonjs/melonJS/files/5011980/index.txt)

**Comment by obiot** [comment] 2020-08-03 03:52
really having a hard time with this one, I literally have no clue on what is happening, and right now, I'm looking at all the commits one by one done since 7.x and doing some trial & errors to pint point the issue

**Comment by siauderman** [comment] 2020-08-03 03:57
I'll try my best to help. So far, couldn't figure it out myself too.

**Comment by obiot** [comment] 2020-08-03 06:17
ok, I found something, I'm not clear still on why there is a difference between the canvas and WebGL renderer, or even why it was working on the 7.x branch, but the issues seems to be related to adding your map to the world container, and where the world bounds is not updated. If you change your code to the the below it's seems to be working on my side (note this is based on the latest 8.0 api, that you are using anyway)

```javascript
tilemap.addTo(me.game.world);
me.game.world.resize(tilemap.getBounds().width, tilemap.getBounds().height);
```

it took me half a day to find this, and I'll see later how to properly fix it, but in the mean time you can look at it and confirm if it does fix your issue. 

but I must say that this is quite an interesting and somehow funny bug to track down :)

**Comment by obiot** [comment] 2020-08-03 08:38
a first fix is in the box, I will keep working on it a bit today or tomorrow, but for your use case you should (Ihope!) find back the same behaviour as previously, let me know.

thank you again for the help on feedback on this !

**Comment by obiot** [comment] 2020-08-06 04:00
Hi @siauderman, done on my side with some further related improvements (see the comments on my last push), any update on your side ?

**Comment by siauderman** [comment] 2020-08-07 02:44
Hi @obiot, been busy with work. Will try it over the National Day weekend.

**Comment by obiot** [comment] 2020-08-07 03:23
National Day ? are you also based in Singapore ? maybe you told me before and I forgot :)

**Comment by siauderman** [comment] 2020-08-08 12:33
> National Day ? are you also based in Singapore ? maybe you told me before and I forgot :)

Ya lah, told you before leh :)

Great! I have managed to get it working (with WebGL 2) at https://customautosys.com/covidgame/web, after making some changes.

The resize is working (although it causes the game to lag whenever it happens). I did not use setViewportBounds in addTo as I didn't want the map centralised (when it's centralised there's also some problem where you have to click to the right of the sprite for the click to register), I manually called me.game.viewport.setBounds and it worked.

The Container coordinates are kind of weird and it seems I have to set the coordinates of the children to (width,height) of the Container. But not a major issue as it's just a matter of arithmetic.

I realised that the random hang bug seemed to be caused by my use of JavascriptObfuscator so I have disabled the obfuscator for now and it doesn't seem to hang now.

I'm gonna test it a bit more before I deploy an update for Android and Electron.

**Comment by obiot** [comment] 2020-08-09 03:58
> > National Day ? are you also based in Singapore ? maybe you told me before and I forgot :)
> 
> Ya lah, told you before leh :)

indeed you did !, Happy National Day !

**Comment by obiot** [comment] 2020-08-09 04:00
> I realised that the random hang bug seemed to be caused by my use of JavascriptObfuscator so I have disabled the obfuscator for now and it doesn't seem to hang now.

when the code go through the obfuscation, do you use the minified of plain version for melonJS ? I guess there must be something either way that goes transformed/obfuscated the wrong way, not sure how to find out though if this is randomely happening .... other way would to keep melonJS intact and just obfuscate your code (after all there is no need for melonJS)

**Comment by siauderman** [comment] 2020-08-09 06:52
I think it's the minified version. I suspect it's just that the obfuscation slows down the code to the point that it lags horribly and hangs.

I think the performance of a game doesn't allow for obfuscation. Never mind, it's quite hard to unscramble minified code anyway.

**Comment by obiot** [comment] 2020-08-12 02:24
bro, I'm going to release the 8.0 version, too long overdue, if any remaining issues related to this ticket, will do a quick 8.1 or 8.0.1 bug fix release.

**Comment by siauderman** [comment] 2020-08-12 12:03
Yes bro. Congrats on another fabulous new release!

**Comment by obiot** [comment] 2020-08-12 13:13
Yes, and thanks to you as well for the help!

**Closed** 2020-09-16 01:47 UTC
