### ISSUE TITLE
Tutorial examples display with browser scrollbars

### ISSUE THREAD

**Issue by fhars** [melonjs/melonJS#1018] opened 2021-03-20 09:35 UTC
#### OS platform / Browser  
Ubuntu 20.04 / Firefox 86.0
 
#### melonJS version 

Whatever is used on http://melonjs.github.io/tutorial-platformer/

#### Bug description  

If you click on any of the "Try it out!" examples in the tutorial, the content is scaled to something slightly larger than the browser viewport, so you get a horizontal and vertical scroll bar.
   
![Bildschirmfoto von 2021-03-20 10-34-04](https://user-images.githubusercontent.com/198941/111865537-f893ba80-8967-11eb-8bf0-0243b3af59e9.png)

**Comment by obiot** [comment] 2021-08-16 07:20
on Firefox 90 I'm not able to reproduce this issue, closing this one.

**Closed by obiot** 2021-08-16 07:20 UTC
Labels: Bug, Support
