### ISSUE TITLE
DebugPanel API page is missing from website

### ISSUE THREAD

**Issue by Hectate** [melonjs/melonJS#987] opened 2020-04-10 14:01 UTC
I was trying to look up the API for the DebugPanel so I could locate an option to decrease the text size. I'm developing a smaller resolution game and the elements of the panel overlap and are unreadable/unusable at these lower sizes. Upon opening the API and searching/clicking on the DebugPanel link, I'm routed to [http://melonjs.github.io/melonJS/docs/me.DebugPanel.html](http://melonjs.github.io/melonJS/docs/me.DebugPanel.html) which generates the github pages 404 error.

Note, I did locate the code for DebugPanel and see that the font is a bitmap font hardcoded; is there a way to alter a setting to render the text smaller?

**Comment by obiot** [comment] 2020-04-11 02:34
bitmapText can be resized using the resize method (note that it takes a scaling ratio as parameter) : file:///Users/obiot/Documents/GitHub/melonJS/docs/me.BitmapText.html#resize

but as for the debug panel, yes you can probably resize the font within the panel but the issue is that the location of the "click" area are mostly hardcoded....  the debugPanel is kind of a happy working-ish mess, I always wanted to rewrite it from scratch and even use a different format (separate html/css module) but never found the time... so we keep pathing it over the time 😖

**Comment by Hectate** [comment] 2020-04-11 02:37
Thanks for the info. I can always upsize for specific debug scenarios if needed too.

**Comment by obiot** [comment] 2020-04-11 06:43
would be nice to have a `-` and `+` hotkey that scale down or up the text indeed

**Comment by obiot** [comment] 2021-09-17 00:18
this was fixed in the latest branch.

**Closed by obiot** 2021-09-17 00:18 UTC
