### ISSUE TITLE
WebGL Render Warning : there is no texture bound to the unit XX

### ISSUE THREAD

**Issue by obiot** [melonjs/melonJS#827] opened 2016-11-04 02:31 UTC
although it's only on windows platforms (no warning on OSX whatever the browser), it's still annoying me. 

When using the WebGL, the console displays the following message :

````
[.Offscreen-For-WebGL-XXXXXXXX]RENDER WARNING: there is no texture bound to the unit XX
````

that seems to be a common issue where a texture is bound before being fully loading :
http://stackoverflow.com/questions/21954036/dartweb-gl-render-warning-texture-bound-to-texture-unit-0-is-not-renderable
http://stackoverflow.com/questions/19722247/webgl-wait-for-texture-to-load/19748905#19748905

but also maybe because we don't use Mips for PoT dimension Texture ?
https://github.com/melonjs/melonJS/blob/master/src/video/webgl/shader.js#L175-L199

**Comment by parasyte** [comment] 2016-11-07 17:42
@obiot Which browser on Windows? I actually have a machine capable of testing this, now. The texture binding is supposed to be handled entirely automatically, but there could be a bug in there somewhere...

Mipmapping is only useful for scaling. It's also incompatible with the default "disable antialiasing" setting; Its only purpose is to increase texture details when scaled smaller than their native resolution, and that's only possible with antialiasing.

**Comment by obiot** [comment] 2016-11-08 00:31
On Chrome ! :)

**Comment by parasyte** [comment] 2016-11-08 01:59
Great! I will look into this when I get home. 😃

**Comment by parasyte** [comment] 2016-11-08 04:58
I see this warning, too. It's caused by the [unrolled loop](https://github.com/melonjs/melonJS/blob/c13f6dea1a3c2f2c7ae725c6520cd9cf31df6807/src/video/webgl/glsl/quad-fragment.glsl.dot#L85-L95) in the fragment shader.

The shader needs to be redone for #637 anyway. (It was a good hack, but it's not well-supported on many platforms. And it will become less useful as WebGL2 rolls out.) So I'll close this in favor of fixing the fragment shader elsewhere.

**Closed by parasyte** 2016-11-08 04:58 UTC

**Comment by obiot** [comment] 2016-11-08 05:26
No quick fix possible though while waiting for the shader to be rewritten one day?

**Comment by parasyte** [comment] 2016-11-08 06:11
Quick fix would be creating a bunch of 1x1 px textures as "placeholders" that get overwritten later. If you want to do that, it's easy enough. I figure the warning is just a warning, and it doesn't really hurt anything.

**Comment by Dillybob92** [comment] 2016-11-14 19:09
@parasyte Looks like this answer is part of your fix:
http://stackoverflow.com/questions/19722247/webgl-wait-for-texture-to-load/19748905#19748905

Just curious, do you know where I can add this at to get rid of the error? I assume somewhere in [here](https://github.com/melonjs/melonJS/blob/c13f6dea1a3c2f2c7ae725c6520cd9cf31df6807/src/video/webgl/glsl/quad-fragment.glsl.dot#L85-L95)?

Is adding the 1x1 pixel thing worse than the 257 errors that get shown in dev console though? I'm getting around 257 of these messages. Not sure if that is impacting the performance or not hehe.

**Comment by parasyte** [comment] 2016-11-14 20:31
Right after these lines: https://github.com/melonjs/melonJS/blob/3.1.0/src/video/webgl/webgl_renderer.js#L87-L88

The first two textures are already populated by those two functions, so you can start a for-loop with index `2`. Something like this, if you just want to copy-pasta from that SO answer:

```javascript
for (var i = 2; i < this.compositor.maxTextures; i++) {
    var tex = gl.createTexture();
    var img = new Uint8Array([ 255, 0, 0, 255 ]);
    gl.activeTexture(gl.TEXTURE0 + i);
    gl.bindTexture(gl.TEXTURE_2D, tex);
    gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, 1, 1, 0, gl.RGBA, gl.UNSIGNED_BYTE, img);
}
```

**Comment by Dillybob92** [comment] 2016-11-15 19:58
Thanks @parasyte  Still seems like the errors still pop up. I'm not sure how to else to debug, but I think the message log errors don't really cause a performance problem (if dev console is closed) which will be majority of the time.  I think you guys said a new webgl renderer was in the works that'll prob be fine for the future :)

**Comment by dtturcotte** [comment] 2018-05-21 03:42
@parasyte I get about 200 of these warnings. I'm using latest version of MelonJS in Chrome. Was this issue fixed somewhere?

**Comment by marcusx2** [comment] 2020-09-15 19:25
So...how do I fix this? I still get 256 warnings.

**Comment by obiot** [comment] 2020-09-16 00:42
Upgrade to the latest 8.0 version, the webgl renderer has been mostly rewritten, and those issues (+ others) are not there anymore.
