### ISSUE TITLE
Controls of the platformer demo stop responding...

### ISSUE THREAD

**Issue by ArgosOz** [melonjs/melonJS#963] opened 2018-12-19 17:19 UTC
The platformer demo controls from http://melonjs.org/ is not working properly. Controls quickly stop responding.

#### OS platform / Browser  
e.g. Mac OS 10.13 / Chrome Version 70.0.3538.102 (Official Build) (64-bit)
 
#### melonJS version 
in theory it should always be the last public one, or the current github version

#### Bug description  
Press w or d, player character moves once and then controls stop responding.

**Comment by obiot** [comment] 2018-12-20 07:53
working perfectly fine on my side.... and tested on macOS using Safari, Chrome and Firefox.

Maybe it's time to upgrade to Mojave :P

Do you have the same issue when running the Platformer not from the main website http://melonjs.github.io/melonJS/examples/platformer/  ? 

Closing this ticket in the mean time, as I'm not able to reproduce the issue.

**Closed by obiot** 2018-12-20 07:53 UTC

**Comment by ArgosOz** [comment] 2018-12-20 13:54
> working perfectly fine on my side.... and tested on macOS using Safari, Chrome and Firefox.
> 
> Maybe it's time to upgrade to Mojave :P
> 
> Do you have the same issue when running the Platformer not from the main website http://melonjs.github.io/melonJS/examples/platformer/ ?
> 
> Closing this ticket in the mean time, as I'm not able to reproduce the issue.

I've disabled all the Chrome extensions and the problem is not there anymore! But still I'll wait for Mojave even though I'm salivating for the dark theme :)

**Comment by ArgosOz** [comment] 2018-12-20 14:13
And the problematic extension is Evernote's Web Clipper, unfortunately not an obscure extension. If you get a weird bug report like mine, please ask if the Evernote extension is installed or not.

**Comment by ArgosOz** [comment] 2018-12-20 22:07
https://discussion.evernote.com/topic/114013-web-clipper-chrome-extension-steals-javascript-keyup-events/

**Comment by obiot** [comment] 2018-12-22 02:45
thank you for the feedback ! Will definitely keep this in mind :)
