### ISSUE TITLE
[WebGL] Texture/Samplers out of range on Linux platform

### ISSUE THREAD

**Issue by Giwayume** [melonjs/melonJS#721] opened 2015-08-04 22:03 UTC
[EDIT] see bottom of the ticket for proper explanation, this is not an issue with the TMX/Hexagonal implementation, but linked to the WebGL Renderer

If you fire up the hexagonal demo in Firefox, you can see flickering around the edges of the tiles, particularly the yellow ones. This behaviour does not happen in Chrome.

I've seen this kind of thing happen in Firefox before when you draw an image to the screen but its coordinates are not an integer.

**Comment by obiot** [comment] 2015-08-05 02:20
oh yeah, this seems awfully opened to floating point values :
https://github.com/melonjs/melonJS/blob/master/src/level/TMXRenderer.js#L606

thanks, I'll see that later !

the hexagonal support is nice, but seems not yet fully mature (see also #706)

**Comment by obiot** [comment] 2015-08-05 03:11
just checked on my side :
- i don't see any flickering on "my Firefox"
- i tested the output of the `tileToPixelCoords` function, it never spits out any floating values (and now that I think about it, that would generate an exception, as the `x` and `y` parameter passed to the `me.Tileset.drawTile()` function are expected to be integer values only)

**Comment by Giwayume** [comment] 2015-08-05 03:19
Might be a Linux thing. Let me check on Windows.

**Comment by Giwayume** [comment] 2015-08-05 03:31
Yep. I've tried Firefox on two different Linux machines and it's happening on both, but it's not happening on Firefox for Windows.

Might be a bug in Firefox, but I've seen this exact same behaviour when messing with the canvas on my own before. I'll look into it briefly.

**Comment by Giwayume** [comment] 2015-08-05 04:15
I have found the issue. In the tile image used, the tiles are 15px wide. However, in `me.TMXHexagonalRenderer`, `this.tilewidth` ends up being 14 in the example.

That one pixel overlap between the next and previous tile is where the flickering occurs, because the browser can't decide which tile's pixels it should be drawing. 

It's the same effect as in a 3d game where you have two textured planes overlapping on the exact same level, and you get a big flickering mess where the game doesn't know which plane to draw.

Changing the tile width in Tiled to 15 (as the tiles are designed) fixes this issue.
http://i.imgur.com/BP4CQea.png

**Comment by obiot** [comment] 2015-08-05 04:27
wow that's nasty ! super good found :p

**Comment by obiot** [comment] 2015-08-05 04:36
are you sure ? it creates some artifacts on the right side of the map, and the two last rows seems to be "out of reach" (the coordinates are not displayed when the mouse is over them)

**Comment by obiot** [comment] 2015-08-05 04:38
wait the mouse over issue seems to be a pre-existing issue, but the artifact remains though :P

**Comment by Giwayume** [comment] 2015-08-05 04:39
I'm not getting any artifacts in the right side of the map on Firefox or Chrome. You got a screenshot?

**Comment by Giwayume** [comment] 2015-08-05 04:43
Mine looks like this:
http://i.imgur.com/D283nir.png

Also the mouse over is working for me?

**Comment by obiot** [comment] 2015-08-05 04:45
see on the right side, I have the same both on FF (windows and OS X) and Safari
![screen shot 2015-08-05 at 12 44 20 pm](https://cloud.githubusercontent.com/assets/4033090/9078371/c2197806-3b6f-11e5-9e5a-17dcad1a7842.png)

**Comment by obiot** [comment] 2015-08-05 04:45
plus with the extra pixel, it does not look really neat, see the additional space between tiles ?

**Comment by Giwayume** [comment] 2015-08-05 04:50
You set it to 15, not 16 right?

**Comment by obiot** [comment] 2015-08-05 04:51
yes of course :)

I wonder if it would not be smarter at this point to open a ticket on the Tiled side to confirm these values :P

**Comment by Giwayume** [comment] 2015-08-05 04:52
I'm getting similar spacing in between tiles like you when I set it to 16, however I still don't get the artifacts on the right. I'll compare this between Windows and Linux tomorrow. Need sleep -__-

**Comment by obiot** [comment] 2015-08-05 05:04
not a bad idea indeed, ttyl!

**Comment by Giwayume** [comment] 2015-08-05 23:54
OK, I have tried windows. Left the tile size the same as in Linux (15x12). 

It turns out Chrome is perfect on Windows, just as it is in Linux.

In Firefox on Windows, I'm not getting the artifacts on the right like you are, however I see slight spacing issue between the tiles. This implementation is all over the place, man.

Windows Comparison:
http://i.imgur.com/aJ0yCJ0.png

**Comment by parasyte** [comment] 2015-08-06 00:59
It looks like non-integer scaling somewhere. Try removing variables, like canvas auto-scaling, to get a baseline. You can always zoom/scale the screenshot with linear interpolation to get a closer look at artifacts per-pixel.

**Comment by obiot** [comment] 2015-09-03 05:05
deferring this one to 3.1.0

**Comment by obiot** [comment] 2016-01-27 01:25
I wonder if this last changes (on master) does help with this issue ?
https://github.com/melonjs/melonJS/commit/6af80f11da8867d844143f94add809b4ad1d69f4

I don't see anything wrong in FF, but I was not seeing anything wrong as well previously (still confused on what is the bug exactly here)

**Comment by obiot** [comment] 2016-01-27 01:28
@Giwayume if you are still out-there, a quick test on your side would be awesome :)

here is the last build:
http://melonjs-builds.s3.amazonaws.com/artifacts/master/1530/build/melonJS.js

**Comment by Giwayume** [comment] 2016-01-28 19:55
Will do when I get a chance

**Comment by Giwayume** [comment] 2016-01-31 17:49
I merged with master and did a grunt build. The problem still exists. Here's an animated gif of what I'm seeing.
![tile_edges_fighting_for_visibility](https://cloud.githubusercontent.com/assets/4075314/12703764/06332d08-c819-11e5-9ca9-05fbcaaa4790.gif)

**Comment by parasyte** [comment] 2016-01-31 19:50
I'm not able to reproduce the flickering on Firefox/Windows 10 (running as a VirtualBox guest on OSX host) or Firefox/OSX. I just used the default canvas renderer, didn't try the WebGL renderer.

On the bright side, I was able to get melonJS built on Windows without any trouble; just a few steps to install `cmder` (full) and `nodejs`, then the normal melonJS build instructions.

**Comment by parasyte** [comment] 2016-01-31 19:51
Oh, I misread the ticket. The flickering is reported to appear on Linux, not Windows. I'll try Ubuntu in VirtualBox after lunch. :)

**Comment by Giwayume** [comment] 2016-01-31 22:54
The demo only works for me on `renderer:me.video.CANVAS`. For WebGL it throws: 
**Error: WebGL: linkProgram: Programs with more than 16 samplers are disallowed on Mesa drivers to avoid crashing.**

So... I don't know whether it happens on WebGL or not.

**Comment by parasyte** [comment] 2016-02-01 04:59
Oh, that's a problem with the demo. It creates too many textures.

**Comment by obiot** [comment] 2016-02-01 05:28
Which is weird actually considering how simple is the demo !

https://github.com/melonjs/melonJS/blob/master/examples/hexagonal/js/resources.js

**Comment by parasyte** [comment] 2016-02-01 05:55
It's not as bad as I thought. It only uses 3 textures. (fill texture, font texture, and tileset)

Probably what's happening is the driver claims to support more than 16 textures, but actually doesn't: https://github.com/melonjs/melonJS/blob/c13f6dea1a3c2f2c7ae725c6520cd9cf31df6807/src/video/webgl/compositor.js#L78-L80

**Comment by obiot** [comment] 2018-06-07 02:40
I'm actually closing this one, not sure what we can do anyway if a driver reports a wrong amount of supported textures, and more than 2 years later, one can assume that things have improved since then.

**Closed by obiot** 2018-06-07 02:40 UTC
Labels: Bug
