### ISSUE TITLE
Conflicts with Facebook SDK

### ISSUE THREAD

**Issue by jdrorrer** [melonjs/melonJS#699] opened 2015-06-26 19:01 UTC
Some of the javascript monkey patching in melonJS conflicts with the Facebook SDK because they're doing some similar things in the SDK, and causes sporadic loading behavior.  The SDK will not load at all in Firefox and sometimes loads in Chrome/Safari, and sometimes not.

Specifically, when I comment out lines 219 to 297 of the following snippet, the Facebook SDK loads perfectly again: https://github.com/melonjs/melonJS/blob/970927095d77c4672f181a05d3d33b79454829b0/src/lang/object.js

Of course, then melonJS no longer works!  Is this an issue you all have run into before?  Any ideas on a workaround for this?  Thanks in advance!

**Comment by parasyte** [comment] 2015-06-26 19:20
Duplicate of #666 

Thanks for the alert.

**Closed by parasyte** 2015-06-26 19:20 UTC
