### ISSUE TITLE
Move scaling, rotation, alpha, etc to me.Renderable

### ISSUE THREAD

**Issue by parasyte** [melonjs/melonJS#335] opened 2013-12-18 19:11 UTC
For discussion: I think the me.Renderable base class should be responsible for all drawing, including scaling, rotation, and opacity/alpha blending.

I'm indifferent about keeping backward compatibility by continuing to support these properties on ObjectEntity.

**Comment by obiot** [comment] 2015-08-04 12:09
considering that we did not really agree here on how to properly do it, I'm moving it to 4.0.0 as well (won't likely happen on 3.0.0)

**Comment by obiot** [comment] 2016-02-22 04:59
hi guys, 

I was looking back at this one and i really wanted to propose the following to address this ticket :

* (Function) `setTransform(scaleX, skewX,  skewY, scaleY, posX, posY)` : which provides a convenience function that mimic the standard [function](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setTransform)
* (Function) `transform(scaleX, skewX,  skewY, scaleY, posX, posY)`, same as above, but add to the already defined transformations instead of resetting them.
* (Function) `scale(x,[y])` (from `me.Renderable) 
* (Function) `rotate(angle)` : that replaces the properties `angle` we had in `me.Renderable
* (Function) `hasTransform()` : returns true if any transform was applied to the object
* (Function) `getTransform()` :  used by renderers to apply transform defined by a renderable

All related properties would then be stored in a mat2d object, allowing then to easily pass back the same object to the [Canvas Renderer](https://github.com/melonjs/melonJS/blob/master/src/video/canvas/canvas_renderer.js#L534) or [WebGL Renderer](https://github.com/melonjs/melonJS/blob/master/src/video/webgl/webgl_renderer.js#L675) `transform` function.

with that, any class inheriting from me.Renderable, just have to focus on drawing whatever they need without having to call something else or a parent function or whatever. As the main loop in the [container object](https://github.com/melonjs/melonJS/blob/master/src/renderable/container.js#L789) would then be in charge of applying any defined transforms before calling the object draw function, so something like that  :
````javascript
           for (var i = this.children.length, obj; i--, (obj = this.children[i]);) {
                hasTranform = obj.hasTransform() || obj.floating;
                if ((obj.inViewport || isFloating) && obj.isRenderable) {
                    if (hasTranform) {
                        // translate to screen coordinates
                        renderer.save();
                        renderer.resetTransform();
                    }

                    // draw the object
                    if (hasTranform) {
                        renderer.transform(obj.getTransform());
                    }
                    obj.draw(renderer, rect);

                    if (hasTranform) {
                        renderer.restore();
                    }

                    this.drawCount++;
                }
            }
````

**Comment by obiot** [comment] 2016-02-22 05:11
to add to this, we do not need to absolutely use a mat2d object within me.Renderable, but at least we need the `getTransform()` function to returns one so that we can use the renderer `transform()` function (looks like the most straightforward way to me)

**Comment by obiot** [comment] 2016-03-13 15:14
would be nice to also mimic `CanvasRenderingContext2D .currentTransform` for this one :
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/currentTransform

and I think we had a ticket for it somewhere, but we could also align our matrix API with the SVG one :
https://developer.mozilla.org/en-US/docs/Web/API/SVGMatrix

or at least add the `flipX/Y`, `skewX/Y`, etc...  functions

**Comment by obiot** [comment] 2016-05-26 05:51
got this baby started !
https://github.com/melonjs/melonJS/commit/eb7cf7319423376b37bf9f386781ea68da7b3abc

so far, working as previoulsy, will keep trying to optimize our code this week :)

**Comment by obiot** [comment] 2016-06-01 09:19
@parasyte @agmcleod 

I managed to greatly simplified the draw function :)
https://github.com/melonjs/melonJS/commit/c30e386a387bfd44e329d23f91e93998c3ce4320

it looks pretty cool and simple now !
https://github.com/melonjs/melonJS/blob/ticket-335/src/renderable/sprite.js#L281-L310

and so far, no regression that I could see compared to the previous implementation (including cumulating both a rotation from texture packer and a regular rotation/scaling)

**Comment by obiot** [comment] 2016-06-01 09:20
i start to really like this ticket :P

next step I'd like to apply the transformation outside of the draw object, and move it to the main loop (like I was trying to explain it in the above pseudo-code)

**Comment by obiot** [comment] 2016-07-08 07:21
so cool, this code :
````javascript
game.PlayScreen = me.ScreenObject.extend({
    /**
     *  action to perform on state change
     */
    onResetEvent: function() {

        //create a new level container
        if (typeof this.levelContainer === "undefined") {
            this.levelContainer = new me.Container();
            this.levelContainer.name = "levelContainer";
        }

        // load our level
        me.levelDirector.loadLevel("map1", {container:this.levelContainer});

        // apply some random transform
        this.levelContainer.transform.translate(this.levelContainer.height / 2, this.levelContainer.width / 2);
        this.levelContainer.transform.rotate(0.1);
        this.levelContainer.transform.scale(1.2);
        this.levelContainer.transform.translate(-this.levelContainer.height / 2, -this.levelContainer.width / 2);

        // add it to the game world
        me.game.world.addChild(this.levelContainer);

[...]

````

now does that :
![container_transform](https://cloud.githubusercontent.com/assets/4033090/16680212/4b4838f6-44ed-11e6-8535-83687c77475c.png)

**Comment by obiot** [comment] 2016-07-08 07:42
@parasyte i'm pretty sure it was already discussed somewhere else, but when scaling on the level rendereing, the result is way better with webgl:
![container_transform_webgl](https://cloud.githubusercontent.com/assets/4033090/16680607/1e33a99c-44f0-11e6-9d3d-7274a3a271ff.png)

with the canvas renderer, you can see those tiny lines between each tiles, where there is nothing with webgl

**Comment by parasyte** [comment] 2016-07-08 07:51
So nice! ☺️ This is actually one of the primary reasons for loading maps into a container. The other reason is to have multiple maps loaded simultaneously. Good work!

... Now if only the background layers would render appropriately ...

**Comment by obiot** [comment] 2016-07-08 07:53
holly molly ! i did not even notice it :P

**Comment by obiot** [comment] 2016-07-08 08:33
@parasyte and by any chance do you remember that discussion about scaling and result differernce between canvas and webgl ?

I think after that ticket I will also work on the alpha issue (where we also have a difference of behavior between the two renderers). to at least provide the option for the canvas one to act as the webgl one (and maybe makes it the default option)

**Comment by obiot** [comment] 2016-07-08 09:54
@parasyte applying the same transformation to the created pattern is gonna be very challenging....
https://developer.mozilla.org/en-US/docs/Web/API/CanvasPattern/setTransform

the only way would be to revamp the imageLayer object to render to an offscreen canvas, to which then we can "safely" apply a transformation. Looks like a bit ugly to me and completely defeating the initial purpose of using create/drawPattern.

**Comment by parasyte** [comment] 2016-07-08 16:49
@obiot This is the comment/ticket that describes some of the differences between WebGL and Canvas: https://github.com/melonjs/melonJS/issues/783#issuecomment-197662230

Looks like `CanvasPattern.setTransform` is only supported in Firefox. :cry: But at least we can do it on all browsers in WebGL! 😄 The pattern object is just a plain ol' texture, and we can transform textures as we please.

* https://github.com/melonjs/melonJS/blob/522b8a07ecfc80c61077295892211668a4a3e13f/src/video/webgl/webgl_renderer.js#L166-L199
* https://github.com/melonjs/melonJS/blob/522b8a07ecfc80c61077295892211668a4a3e13f/src/video/webgl/webgl_renderer.js#L328-L343

**Comment by obiot** [comment] 2016-07-08 17:40
i think we managed properly already the pixel alignement when rendering, the issue here appears when the canvas is rotated, which produce some kind of aliasing on the edge of each tiles with the canvas renderer, but not with the webgl one. See the first picture vs the second one

**Comment by parasyte** [comment] 2016-07-08 18:50
Yeah, I saw it ... WebGLRenderer doesn't exhibit the texture seam behavior because we use the `NEAREST` texture filter. I assume if you enabled antiAlias in WebGL, you would see the seams.

I don't remember seeing the pixel alignment fix, though? Maybe that changed something in Canvas enough to create the seams.

**Comment by obiot** [comment] 2016-07-08 19:05
indeed yes, with antiAlias enabled, I can see the same behvior with webGL, But i just spent the last hour trying to round pixel wherever possible with a combination of `x | 0` or `~~(0.5 +x)`, and i could not get it right with the canvas renderer.... i'm kind of lost of where it's missing

**Comment by parasyte** [comment] 2016-07-08 19:57
The typical solution for texture seams with anti-aliasing enabled is making the textures slightly larger (like adding a 1-texel border around the quad) so that there is some slight overlap.

**Comment by obiot** [comment] 2016-07-09 18:25
changing the `drawTile` function as follow indeed fixes the issue with the Canvas renderer :
````javascript
    // draw the tile
            renderer.drawImage(
                this.image,
                offset.x, offset.y,
                this.tilewidth, this.tileheight,
                dx, dy,
                this.tilewidth + 1, this.tileheight + 1
            );
````

but it looks more like a workaround (by adding "padding") rather than a proper fix

**Comment by obiot** [comment] 2016-07-09 18:26
i could not see any artefacts/side-effects, when the tilemap is not rotated though

**Comment by parasyte** [comment] 2016-07-09 19:35
You can also use non-integer size like `+ 0.5`. That should also fix the seams, without introducing extra aliasing.

**Comment by obiot** [comment] 2016-07-09 19:51
i tried with `0.5` there is still a seam :P I guess I would commit that change then, what do you think ?

**Comment by parasyte** [comment] 2016-07-09 19:52
I would say commit it, but only for `CanvasRenderer`.

**Comment by obiot** [comment] 2016-07-09 20:08
i will sleep on it first, and do some google search tomorrow before doing anything :)

**Comment by obiot** [comment] 2016-07-11 13:26
so I came up with this fix, trying to keep it as "generic" as possible. if you could give it a quick review :)

**Comment by obiot** [comment] 2016-07-11 13:36
i still don't like it though, but after 2 days on it, I really have no clue on how to make it better.... except than rendering the layer offscreen and then transform it (which is not as well a good idea)

**Comment by obiot** [comment] 2016-07-11 13:37
we really need to push our webgl renderer forward at a point where it can replace the canvas one.

we need you Jason !!!!

**Comment by parasyte** [comment] 2016-07-12 03:22
I give it :+1: for review. It's not ideal, but definitely good enough when optional.

The WebGL compositor needs a slight redesign to work with mobile UAs 😅. It will be a performance hit on Desktop, sadly. But I guess worth it for higher compatibility.

**Comment by obiot** [comment] 2016-07-12 06:39
cool, thanks :)

so this branch is almost ready for merging then. API wise it still (almost) provides backward compatibility, and the one thing left I want to add is a `autoTransform` attribute that will automatically translate the renderable based on his anchorPoint and apply any define transform. Somehting like the follwoing in the main container loop :
````javascript
for (all child in container) {
    [ ... ]

    if (child.applyTransform === true) {
        child.translate(anchorPoint);
        renderer.transform(child.transform);
    }
    child.draw(renderer);

    [ ... ]
}

the flag being ON by default in `me.Renderable`, but then turned back off by default (at least in the beginning) in all built-in object to avoid breaking further things.

**Comment by obiot** [comment] 2016-07-29 02:59
so guys, I'm ready to merge this one. There is still some work to do as some of the melonJS pre-defined object still need some update to work with it (so the feature is forced to disable for those), but in the current state, it does not bring any regression, and works just fine for new objects created in a game (it works beautifully in my current game).

**Comment by obiot** [comment] 2016-08-31 04:07
so one month later, it's time to merge this baby, I'm doing this today as i"m back home until tomorrow (then I can elope again until next week!)

**Closed** 2016-08-31 04:11 UTC
