### ISSUE TITLE
Tutorial doesn't works with latest version of melonJS

### ISSUE THREAD

**Issue by MikeVelazcoMtz** [melonjs/melonJS#974] opened 2019-03-06 20:20 UTC
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
OS X / Google Chrome Version 72.0.3626.119 (Official Build) (64-bit)

 
#### melonJS version 
Latest version

#### Bug description  
Tutorial doesn't works when updating melonJS

#### Steps to reproduce the bug
http://melonjs.github.io/tutorial-platformer/#part3

#### Console log Extract 
melonJS 6.4.0 | http://melonjs.org
melonjs.js:16494 CANVAS | Web Audio | pixel ratio 2 | desktop | landscape-primary | en-US
melonjs.js:16502 resolution: requested 640x480, got 1707x480
melonjs.js:30714 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu
setupAudioContext @ melonjs.js:30714
volume @ melonjs.js:28379
me.audio.api.load @ melonjs.js:15686
me.loader.api.load @ melonjs.js:14252
me.loader.api.preload @ melonjs.js:14175
onload @ game.js:22
onReady @ (index):47
me.device.api._domReady @ melonjs.js:484
melonjs.js:32921 me.BitmapFont is deprecated, please use me.BitmapText
melonjs.js:1836 Uncaught TypeError: Cannot read property 'cameras' of undefined
    at Object.me.game.api.draw [as _patched] (melonjs.js:1836)
    at Object.<anonymous> (debugPanel.js:307)
    at Object.defineProperty.value [as draw] (melonjs.js:31530)
    at _renderFrame (melonjs.js:12947)
me.game.api.draw @ melonjs.js:1836
(anonymous) @ debugPanel.js:307
Object.defineProperty.value @ melonjs.js:31530
_renderFrame @ melonjs.js:12947
requestAnimationFrame (async)
_startRunLoop @ melonjs.js:12910
_switchState @ melonjs.js:12987
setTimeout (async)
api.defer @ melonjs.js:22534
me.state.api.change @ melonjs.js:13419
me.loader.api.preload @ melonjs.js:14188
onload @ game.js:22
onReady @ (index):47
me.device.api._domReady @ melonjs.js:484
melonjs.js:32859 me.ScreenObject is deprecated, please use me.Stage
melonjs.js:32859 me.ScreenObject is deprecated, please use me.Stage
melonjs.js:17328 Spritesheet Texture for image: http://localhost:8000/data/img/map/area01_level_tiles.png is not divisible by 32x32, truncating effective size to 640x224
parseFromSpriteSheet @ melonjs.js:17328
init @ melonjs.js:17220
Class @ melonjs.js:201
get @ melonjs.js:17667
init @ melonjs.js:24712
Class @ melonjs.js:201
readTileset @ melonjs.js:26144
(anonymous) @ melonjs.js:26359
readMapObjects @ melonjs.js:26357
getLayers @ melonjs.js:26604
addTo @ melonjs.js:26438
loadTMXLevel @ melonjs.js:26720
safeLoadLevel @ melonjs.js:26670
me.levelDirector.api.loadLevel @ melonjs.js:26856
onResetEvent @ play.js:7
reset @ melonjs.js:12805
_switchState @ melonjs.js:12983
setTimeout (async)
api.defer @ melonjs.js:22534
me.state.api.change @ melonjs.js:13419
loaded @ game.js:34
(anonymous) @ melonjs.js:13718
setTimeout (async)
checkLoadStatus @ melonjs.js:13717
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
me.loader.api.preload @ melonjs.js:14192
onload @ game.js:22
onReady @ (index):47
me.device.api._domReady @ melonjs.js:484
melonjs.js:17682 [Texture] http://localhost:8000/data/img/map/area01_level_tiles.png is not a POT texture (640x241)
set @ melonjs.js:17682
get @ melonjs.js:17667
init @ melonjs.js:24712
Class @ melonjs.js:201
readTileset @ melonjs.js:26144
(anonymous) @ melonjs.js:26359
readMapObjects @ melonjs.js:26357
getLayers @ melonjs.js:26604
addTo @ melonjs.js:26438
loadTMXLevel @ melonjs.js:26720
safeLoadLevel @ melonjs.js:26670
me.levelDirector.api.loadLevel @ melonjs.js:26856
onResetEvent @ play.js:7
reset @ melonjs.js:12805
_switchState @ melonjs.js:12983
setTimeout (async)
api.defer @ melonjs.js:22534
me.state.api.change @ melonjs.js:13419
loaded @ game.js:34
(anonymous) @ melonjs.js:13718
setTimeout (async)
checkLoadStatus @ melonjs.js:13717
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
me.loader.api.preload @ melonjs.js:14192
onload @ game.js:22
onReady @ (index):47
me.device.api._domReady @ melonjs.js:484
melonjs.js:1836 Uncaught TypeError: Cannot read property 'cameras' of undefined
    at Object.me.game.api.draw [as _patched] (melonjs.js:1836)
    at Object.<anonymous> (debugPanel.js:307)
    at Object.defineProperty.value [as draw] (melonjs.js:31530)
    at _renderFrame (melonjs.js:12947)
me.game.api.draw @ melonjs.js:1836
(anonymous) @ debugPanel.js:307
Object.defineProperty.value @ melonjs.js:31530
_renderFrame @ melonjs.js:12947
requestAnimationFrame (async)
_startRunLoop @ melonjs.js:12910
_switchState @ melonjs.js:12987
setTimeout (async)
api.defer @ melonjs.js:22534
me.state.api.change @ melonjs.js:13419
loaded @ game.js:34
(anonymous) @ melonjs.js:13718
setTimeout (async)
checkLoadStatus @ melonjs.js:13717
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
(anonymous) @ melonjs.js:13728
setTimeout (async)
checkLoadStatus @ melonjs.js:13727
me.loader.api.preload @ melonjs.js:14192
onload @ game.js:22
onReady @ (index):47
me.device.api._domReady @ melonjs.js:484

**Comment by obiot** [comment] 2019-03-09 04:32
actually the issue is caused by the debugPanel that also needs to be updated, replace your version by the latest here, and the issue should be fixed :
https://github.com/melonjs/melonJS/releases/download/6.4.0/debugPanel.js

thank you :P

**Closed by obiot** 2019-03-09 04:32 UTC
