### ISSUE TITLE
WebGL render loses context / crashes

### ISSUE THREAD

**Issue by geNAZt** [melonjs/melonJS#1000] opened 2020-06-01 10:50 UTC
If you are submitting a bug report, please respect the below template :

#### OS platform / Browser  
Windows 10 19635.1 / Chrome 83.0.4103.61
 
#### melonJS version 
7.1.1

#### Bug description  
Using the webGL renderer crashes after 20-30 seconds usage. Canvas based renderer is fine.

#### Steps to reproduce the bug
Current live bug: https://doublechins.genazt.me/

Simply load the links and wait around 20-30 seconds. It should crash and reset the GPU

#### Console log Extract 
i get this warning in the console:

WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

**Comment by obiot** [comment] 2020-06-01 11:03
Thanks !! this is an interesting one, as I'm not able to reproduce it on OS X, and the 7.x branch does handle context loss in WebGL.

Could you maybe try with the latest 8.x branch (we have some significant rewrite on the WebGL renderer) ? if you don't have a build environment setup, I just shared a stable build the other day here (do notice the changes on how gravity is now setup/applied):
https://www.html5gamedevs.com/topic/45518-device-orientation/?tab=comments#comment-251568

thank you !

**Comment by geNAZt** [comment] 2020-06-01 11:39
I updated to 8.0.0-dev and it seems fine except it somehow broke the wrapper functionality. Its updated at https://doublechins.genazt.me/ just scroll down (because the canvas is not inside the given div anymore)

**Comment by geNAZt** [comment] 2020-06-01 11:41
Ok, it crashed again, just took it a little longer :D 

Just ran down and it crashed. Console log:

ArrowDown {agent: {…}, device: {…}, event: {…}, game: {…}, Object: ƒ, …}
doublechins.genazt.me/:1 WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost

**Comment by obiot** [comment] 2020-06-02 02:18
> I updated to 8.0.0-dev and it seems fine except it somehow broke the wrapper functionality. Its updated at https://doublechins.genazt.me/ just scroll down (because the canvas is not inside the given div anymore)

can you try to set `useParentDOMSize` to false in your video init string ?  that should fix it

**Comment by obiot** [comment] 2020-06-03 13:12
I'm really having a hard time finding the issue here, when I'm simulating a context loss, and then simulating a context restore, the game properly resume without crashing, as expected. I tried Safari, Chrome, FF, and they are all fine,

on your machine, is this behaviour the same whatever browser you use ?

**Comment by geNAZt** [comment] 2020-06-03 13:45
Yes, is there a debug option for webgl in some browsers so I can check
which instructions had been made to the GPU?

Olivier Biot <notifications@github.com> schrieb am Mi., 3. Juni 2020, 15:13:

**Comment by obiot** [comment] 2020-06-03 13:49
if you run this in the console.log 
```javascript
var ctx = me.video.renderer.context.getExtension('WEBGL_lose_context');
ctx.loseContext();
```
to simulate a context loss, 

and then 
```javascript
ctx.restoreContext();
```
does the game also crash or does not "un-freeze" ? these two will have the same effect when done by the browser and trigger the same event that melons is listening to, to handle the context loss/restore.

else, I'm not sure how/what to look for here honestly in terms of debugging this with the GPU.

**Comment by obiot** [comment] 2020-06-05 07:22
some update on my side, I finally managed to test on Windows 10 and indeed I confirm that your game crashes after a while, however all I'm seeing is the screen turning black but without any exception on the console or any messages related especially to context lost/restore, and the game still seems to running as the game keep logging player movement.

I tried then to put some debug points here and there but as everything is currently minified/obfuscated it was quite complicated so what I did is to run all the current melonJS example every time trying all canvas/webgl1/wegbl2 renderer mode, using Edge (83.0.478.44), Crome (83.0.4103.97) and Firefox (72.0.2) and let them for a few minutes.....  conclusion is/was that I never experienced any similar crash and everything was running nice and smooth, so I really have no idea here about what to do to be honest, are you really sure that the crash could not be linked to all the other things that are integrated with your games ?

**Comment by obiot** [comment] 2020-06-06 10:06
Just saw this : https://windowsreport.com/microsoft-edge-black-screen/

I wonder if maybe this is the issue as it seems to be driver related

**Comment by geNAZt** [comment] 2020-06-06 12:47
Its basicly the isometric_rpg sample with another map loaded onto it. Currently there are no modifications in the rendering itself. But why does it work with other 3D stuff? I only have the problem with WebGL stuff on windows? DirectX, openGL, Vulkan applications all work without any problems (i also play on this computer).

Yeah the game itself is compiled within angular so its minified and chunked up with webpack. 

But when i look at the example i don't get the crashes. Maybe its due to the Map size? or the viewport?

**Comment by obiot** [comment] 2020-06-07 01:36
Can you share your map and tileset ? Maybe a map size indeed, how big is it ?

**Comment by obiot** [comment] 2020-06-10 02:27
@geNAZt any update ?

to valide if this is a windows browser issue or/and melons specific, did you try any other WebGL based stuff ?  (here is one https://akirodic.com/p/jellyfish/)

Also using the latest 8.0 development version, could you try the different renderer  ?
[melonjs8.0-dev.zip](https://github.com/melonjs/melonJS/files/4755836/melonjs8.0-dev.zip)

renderer can be forced using `renderer : me.video.CANVAS` or `renderer : me.video.WEBGL` and for WebGL2 you need to use/add `preferWebGL1 : false`.

also I would love to see the console output with your GPU information, and if possible do update your graphic card drivers before doing anything of this.

thanks !

Note : remember to also try with `useParentDOMSize` to false in your video init string (should fix the canvas position itself)

**Comment by obiot** [comment] 2020-07-22 06:12
Any further feedback here ?

FYI, here is below the very latest build, as div related position/resizing has been "optimized" and `userParentDomSize` now deprecated and removed, I would be interested to see if this version does address your issues :
https://github.com/melonjs/melonJS/files/4958018/melonjs-8.0-dev.zip

**Comment by obiot** [comment] 2020-08-03 08:51
@geNAZt I'm not getting further feedback from you on this, so either the latest build worked for you, or else we have a couple of fixes that I believe are/were related through issues #1010 and #1003.

if the latter, unless you cannot built the latest version from GitHub, I'll happily shared a build version here, let me know. in the mean time, I'm closing this ticket, will re-open if necessary and not covered by the previous fix and/or the two others mentioned here.

**Closed by obiot** 2020-08-03 08:51 UTC
